
DATA:
    LABEL_MAP_PATH: 'data/label_map.txt'

MODEL:
    CKPT_PATH: 'data/checkpoints/rgb_imagenet/model.ckpt'
    CKPT_PATH_WITH_ZERO_PERT: '/data/DL/Adversarial/kinetics-i3d/result/generalization/model_gen_untargeted_ce_loss_reg/model_step_00000'
    

SINGLE_VIDEO_ATTACK:

    TARGETED_ATTACK: True
    TARGETED_CLASS: 'javelin throw'
    IMPROVE_ADV_LOSS: True
    PROB_MARGIN: 0.05
    USE_LOGITS: True
    MAX_NUM_STEP: 10
    
    LAMBDA: 1.0
    BETA_1: 0.5
    BETA_2: 0.5
    BATCH_SIZE: 1
    
    CYCLIC_ATTACK: False
    
    PKL_RESULT_PATH: 'result/videos_for_tests/npy/tmp/'
    NPY_PATH: 'data/videos_for_tests/npy/'
    
    TF_RECORDS_TRAIN_PATH: '/data/DL/Adversarial/ActivityNet/Crawler/Kinetics/database/tfrecord_uint8/val/'
    TF_RECORDS_VAL_PATH: '/data/DL/Adversarial/ActivityNet/Crawler/Kinetics/database/tfrecord_uint8/test/'

CLASS_GEN_ATTACK:

    TARGETED_ATTACK: False
    TARGETED_CLASS: 'javelin throw'
    IMPROVE_ADV_LOSS: True
    PROB_MARGIN: 0.05
    USE_LOGITS: True
    MAX_NUM_STEP: 10000
    
    LAMBDA: 1.0
    BETA_1: 0.5
    BETA_2: 0.5
    BATCH_SIZE: 8
    
    CYCLIC_ATTACK: False
    
    PKL_RESULT_PATH: 'result/generalization/single_class/'
    NPY_PATH: 'data/videos_for_tests/npy/'
    
    TF_RECORDS_TRAIN_PATH: ['/data/DL/Adversarial/ActivityNet/Crawler/Kinetics/database/tfrecord_uint8/train/using computer/']
    TF_RECORDS_VAL_PATH: ['/data/DL/Adversarial/ActivityNet/Crawler/Kinetics/database/tfrecord_uint8/val/using computer/',
                          '/data/DL/Adversarial/ActivityNet/Crawler/Kinetics/database/tfrecord_uint8/test/using computer/']
    
    
UNIVERSAL_ATTACK:

    TARGETED_ATTACK: False
    TARGETED_CLASS: 'javelin throw'
    IMPROVE_ADV_LOSS: False #False- cross entropy loss
    PROB_MARGIN: 0.05
    USE_LOGITS: True
    MAX_NUM_STEP: 10000
    
    LAMBDA: 1 #1 # 0.1 #0.1 #10.0 #100.0 - for targeted
    BETA_1: 1 #1 #0.5
    BETA_2: 0 #0.5
    BATCH_SIZE: 8
    
    CYCLIC_ATTACK: False
    
    PKL_RESULT_PATH: 'result/generalization/universal/L12_loss'#'result/generalization/model_gen_untargeted_ce_loss_reg/'
    NPY_PATH: 'data/videos_for_tests/npy/'
    
    TF_RECORDS_TRAIN_PATH: ['/home/ubadmin/pony/database/Kinetics/tfrecord_uint8/val/all_cls_shuffle/']
    TF_RECORDS_VAL_PATH: ['/home/ubadmin/pony/database/Kinetics/tfrecord_uint8/test/all_cls_shuffle/']

    NUM_OF_TRAIN_TF_RECORDS: 300
    NUM_OF_VAL_TF_RECORDS: 40
    
    NUM_OF_VID_EACH_TF_RECORDS: 50